# Generated by Django 6.0.3 on 2026-03-17 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='stories.chapter'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
