# Generated by Django 6.0.3 on 2026-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
    ]
