# Generated by Django 6.0.3 on 2026-03-24 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_chapter_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='voice',
            field=models.CharField(default='banmai', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='stories.chapter'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
